# Site settings
title: Mehdi El Amri
description: mehdi.elamri@emsi-edu.ma

url: http://elamrimehdi.github.io/

about_title: About
projects_title: Home

# User settings
user_description_appendix: |
  I created this site to write about my interests: startups and entrepreneurship, design, data-intensive applications,
  functional programming, AR/VR, and machine learning. Above all, I love using computers to solve big problems.

  I built this site in [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so if
  you like it, feel free to fork it on [GitHub][github] and make your own version.

  [github]: https://github.com/lrassaby/lrassaby.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: mehdi.elamri@emsi-edu.ma
linkedin: meelamri
github: ElAmriMehdi
#angellist: rassaby

relevant_tags: ['IA', 'tutorials', 'events', 'music']

resume_url: https://docs.google.com/document/d/1dJIboSF-ktdaP28DDu-gcuOW1SCCnkSdqtodJGwYkaA/export?format=pdf
music_resume_url: https://docs.google.com/document/d/17F3g8jx2UHby77P7shJlsKAW2Efasuc1HuQ3Ro3v3zI/export?format=pdf

author: Mehdi El Amri
author_title: engineer student
author_photo: profile-photo.jpg
user_description_short: |
  Je suis élève ingénieur spécialité MIAGE à l'ecole marocaine des sciences de l'ingénieur et à l'université nice sophia antipolis. Passioné par le web, le cloud, et l'intelligence. 


  Loin de mon clavier, j'écoute beaoucp de musique :) 




## Disqus
##disqus_identifier: rassaby

## Tracker
##google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,Mehdi El Amri'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
