# Site settings
title: Mehdi El Amri
description: mehdi.elamri@emsi-edu.ma

url: http://elamrimehdi.github.io/

about_title: About
projects_title: Home

# User settings
user_description_appendix: |
  
  J'ai crée ce site pour partager mes passions: Le rôle du système informatique dans l'entreprise, l'intelligence artificielle, le web et autres. 
  

email: mehdi.elamri@emsi-edu.ma
linkedin: meelamri
github: ElAmriMehdi
#angellist: rassaby

relevant_tags: ['IA', 'tutorials', 'events']

resume_url: https://docs.google.com/document/d/1dJIboSF-ktdaP28DDu-gcuOW1SCCnkSdqtodJGwYkaA/export?format=pdf
music_resume_url: https://docs.google.com/document/d/17F3g8jx2UHby77P7shJlsKAW2Efasuc1HuQ3Ro3v3zI/export?format=pdf

author: Mehdi El Amri
author_title: engineer student
author_photo: profile-photo.jpg
user_description_short: |
  Je suis élève ingénieur spécialité MIAGE à l'ecole marocaine des sciences de l'ingénieur et à l'université nice sophia antipolis. Passioné par le web, le cloud, et l'intelligence artificielle. 


  Loin de mon clavier, je suis magicien et j'écoute beaucoup de musique :) 




## Disqus
##disqus_identifier: rassaby

## Tracker
##google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,Mehdi El Amri'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
