# Site settings
title: Mehdi El Amri
description: mehdi.elamri@emsi-edu.ma

url: http://elamrimehdi.github.io/

about_title: About
timetable_title: Timetable
projects_title: Home


# User settings
user_description_appendix: |
  

email: mehdi.elamri@emsi-edu.ma
linkedin: meelamri
github: ElAmriMehdi
#angellist: rassaby

relevant_tags: ['tutorials']

resume_url: https://drive.google.com/file/d/1b1TJH-L1jPzHmjeWBQZJwTlkxf_nfIqz/view?usp=sharing


author: Mehdi El Amri
author_title: mehdi.elamri@emsi-edu.ma
author_photo: profile-photo.jpg
user_description_short: |
  Je suis élève ingénieur spécialité MIAGE à l'ecole marocaine des sciences de l'ingénieur et à l'université nice sophia antipolis. Passioné par le web, le cloud, et l'intelligence artificielle. Et loin de mon clavier, je suis magicien et j'écoute beaucoup de musique :) 




## Disqus
##disqus_identifier: rassaby

## Tracker
##google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,Mehdi El Amri'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'
timetable_url: '/timetable'

plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
